### PR TITLE
Make package compatible with Laravel 5

### PR DESCRIPTION
**Pull request by markcameron**
I created this in a `2.0` branch to automatically get a `2.0.x` version on Packagist but I don't seem to be able to make a pull request to anything other than existing branches on your repo.

You can tag it as a new version in master or create branches for each version, as you wish.

I didn't update the `README.md` since it all depends on what version you tag it as.

I updated the folder structure to be *PSR-4* compliant since *Laravel 5* moved to that.

### CODE REVIEW

**Comment by that0n3guy** [comment]
I'm a little low on time lately.  I've marked you as a collaborator.  Are you able to do what you need now?

**Comment by markcameron** [comment]
Thanks, yeah I believe so! Only thing would be updating the package on packagist, don't know if you ever got round to setting up the Service/Webhook in GitHub?

**Comment by that0n3guy** [comment]
Yup, i set i up a while ago.  I suppose we will see if it worked :).

**Comment by markcameron** [comment]
Nice thanks. All worked out!

**Pull request closed without merging**
